title: ""
email: offici5lcontact@proton.me
description: ""
baseurl: ""
url: "https://offici5l.github.io"

# Social links
github_username: offici5l
twitter_username: offici5l
telegram_username: Offici5l_Channel

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
  articles:
    output: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

