name: Update Projects JSON with Public Repositories

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  actions: read

jobs:
  update-projects-json:
    runs-on: ubuntu-latest
    name: Update Projects JSON

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch public repositories data
        id: fetch-repos
        run: |
          echo "Fetching data from GitHub API..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/users/${{ github.repository_owner }}/repos?type=public&sort=updated&per_page=100" > repos.json

      - name: Generate projects.json in docs folder
        run: |
          mkdir -p docs
          jq '[.[] | 
            select(.private == false) | 
            select(.description != null and (.description | length > 0)) | 
            {
              name: .name,
              html_url: .html_url,
              description: .description  
            }
          ]' repos.json > docs/projects.json

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add docs/projects.json
          git commit -m "Always update projects.json - $(date +'%Y-%m-%d %H:%M:%S') by GitHub Actions" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Success notification
        run: |
          echo "Operation completed! projects.json was generated and pushed (if changed)."